// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TesteDeliverIT.DAL.Models;

namespace TesteDeliverIT.DAL.Migrations
{
    [DbContext(typeof(DeliverContext))]
    [Migration("20201209234208_adiciona-conta-atraso")]
    partial class adicionacontaatraso
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TesteDeliverIT.DTO.ContaAtrasoDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DiaMinimoAtraso")
                        .HasColumnType("integer");

                    b.Property<decimal>("JurosPorDia")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PorcentagemMulta")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ContaAtraso");
                });

            modelBuilder.Entity("TesteDeliverIT.DTO.ContaDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int>("QtdDiasAtraso")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorCorrigido")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Conta");
                });
#pragma warning restore 612, 618
        }
    }
}
